### ISSUE TITLE
Add functionality for cloning and checkout

### ISSUE THREAD

**Issue by jenniferlindberg** [andnil5/-dd2480-grp12-assignment2#17]
Add commands that perform git cloning and git checkout in server.

**Comment by majate** [comment]
Is this considered fixed now?

**Comment by majate** [comment]
Is this considered fixed now? @jenniferlindberg  @omidhzr

**Comment by andnil5** [comment]
I think so :)

**Comment by omidhzr** [comment]
yes ma'am! ;)
